//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MS_Post
    {
        public System.Guid post_id { get; set; }
        public string post_content { get; set; }
    }
}
